@hostname = https://srp-planning.onrender.com



get {{hostname}}

####

get {{ hostname }}/api/warehouse


###
post {{hostname}}/rm
Content-Type: application/json

{
    "_id": "62fc5fb6ae01805dfa884c21",
    "object_id": "5851990100",
    "source_category": "3rd-Plastic",
    "rm_category": "INJECTION PART",
    "sis_code": "RMMRF-5851990100-T-HLDR",
    "material_name": "TUBE HOLDER_40MM",
    "unit": "PC"
}

###
get http://localhost:5000/api/skus


###
post http://localhost:5000/api/createwarehouse
Content-Type: : application/json

{
    "name":"Samba samba", "space": 5000, "description":"some samba"
}



###

PATCH {{hostname}}/6343a1682a6396394210966b
Content-Type: application/json

{
    "description": "Koushik has to get and verify the closing balance of Liners from Akash"
}

###

delete {{hostname}}/api/rm/63650818b3a865e065531cbf

###

post http://localhost:5000/api/fgprodmany
Content-Type: application/json

[
    {
        "sku": "6353e2a84d7810d0a971abbf",
        "quantity": 20,
        "date": "2016-05-05"
    },
    {
        "sku": "6353e2a84d7810d0a971abbf",
        "quantity": 30,
        "date": "2016-05-05"
    }
]


###
get http://localhost:5000/api/rms



###
get http://localhost:5000/api/getDailyFGProduction/?startDate=2022-09-22&endDate=2022-05-22
# get data with date range


###
post http://localhost:5000/api/testing
Content-Type: application/json

{
    "b":"hello"
}