@hostname = https://srp-planning.onrender.com



get {{hostname}}

####

get {{ hostname }}/api/warehouse


###
post {{hostname}}/rm
Content-Type: application/json

{
    
    "object_id": "kkkkkkkkkk",
    "source_category": "3rd-Plastic",
    "rm_category": "INJECTION PART",
    "sis_code": "RMMRF-5851990100-T-HLDR",
    "material_name": "TUBE HOLDER_40MM",
    "unit": "PC"
}

###

post http://localhost:5000/api/rm
Content-Type: : application/json

{
    "object_id" : "180000000000",
    # "source_category" : "L",
    # "rm_category" : "",
    # "sis_code" : "RMMRF-180000000000",
    # "material_name" : "Super Glue",
    # "unit" : "ml",
    # "sap_code" : "180000000000"
}

###


post http://localhost:5000/api/createwarehouse
Content-Type: : application/json

{
    "name":"Samba samba", "space": 5000, "description":"some samba"
}

###
get http://localhost:5000/api/rms



###

PATCH {{hostname}}/6343a1682a6396394210966b
Content-Type: application/json

{
    "description": "Koushik has to get and verify the closing balance of Liners from Akash"
}

###

delete {{hostname}}/api/rm/63650818b3a865e065531cbf

###

post http://localhost:5000/api/fgprodmany
Content-Type: application/json

[
    {
        "sku": "6353e2a84d7810d0a971abbf",
        "quantity": 20,
        "date": "2016-05-05"
    },
    {
        "sku": "6353e2a84d7810d0a971abbf",
        "quantity": 30,
        "date": "2016-05-05"
    }
]


###
get http://localhost:5000/api/rms



###
get http://localhost:5000/api/getDailyFGProduction/?startDate=2022-08-22&endDate=2022-08-30
# get data with date range


###
post http://localhost:5000/api/testing
Content-Type: application/json



###
get http://localhost:5000/api/sfgBOM/6395e2fcf908b61d08bf579c



###
post http://localhost:5000/api/createSFGBOM
Content-Type: application/json

{
    "object_id": "6353e2a84d7810d0a971abbf",
    "source_category": "F",
    "sis_code": "x355334",
    "material_name" : "bla-Bla",
    "children" : [
        {
            "object_id" : "6353cd5a4d7810d0a95984f3",
            "model_type" : "RM",
            "quantity" : 4
        }
    ]
}


###
get http://localhost:5000/api/getSfgSourceCategory


###
post http://localhost:5000/api/createSfgSourceCategory
Content-Type: application/json

{
    "source_category" : "Phantom"
}

###
post http://localhost:5000/api/createSfgCategory
Content-Type: application/json

{
    "sfg_category" : "Phantom"
}


###
get http://localhost:5000/api/getThirdPartyPlasticActualBOM

###


get http://localhost:5000/api/getThirdPartyMetalSheetsBOM
###


post http://localhost:5000/api/supplierInsertMany
Content-Type: application/json

[
    {
    "supplierID": "SUP010041",
    "supplierName": "WANHUA CHEMICAL (SINGAPORE) PTE. LTD.",
    "supplierEmail": "WANHUA@china.com",
    "supplierAddress": "Somewhere at turkey",
    "supplierContactPerson": "Mr. WANHUA",
    "supplierContactPersonPhoneNumber": 124578601,
    "supplierCategory": "import"
    },
    {
    "supplierID": "SUP010042",
    "supplierName": "XI'AN HONGTAI CO LTD",
    "supplierEmail": "XI'AN@china.com",
    "supplierAddress": "Somewhere at turkey",
    "supplierContactPerson": "Mr. XI'AN",
    "supplierContactPersonPhoneNumber": 124578602,
    "supplierCategory": "import"
    },
    {
    "supplierID": "SUP010043",
    "supplierName": "YANTAI TIBRIGHT NEW MATERIALS CO., LTD",
    "supplierEmail": "YANTAI@china.com",
    "supplierAddress": "Somewhere at turkey",
    "supplierContactPerson": "Mr. YANTAI",
    "supplierContactPersonPhoneNumber": 124578603,
    "supplierCategory": "import"
    },
    {
    "supplierID": "SUP010044",
    "supplierName": "ZHUHAI SPEEDBIRD PVC FLIM LAMINATED METAL SHEET CO LTD",
    "supplierEmail": "ZHUHAI@china.com",
    "supplierAddress": "Somewhere at turkey",
    "supplierContactPerson": "Mr. ZHUHAI",
    "supplierContactPersonPhoneNumber": 124578604,
    "supplierCategory": "import"
    }
]
###

getAllSuppliers
post http://localhost:5000/api/createPhantomPart
Content-Type: application/json

{
  "object_id": "5660200247",
  "material_name": "Door Liner (Deep)-243R, 273R",
  "source_category": "phantom",
  "sfg_category": "phantom",
  "sap_code": "5660200247",
  "sis_code": "phantom-5660200247",
  "substitutes": [
    { "object_id": "6398657223328b7eeff9243f", "model_type": "SFGBOM" },
    { "object_id": "639b10a9271634c6f49fe5ae", "model_type": "SFGBOM" }
  ]
}

###
post http://localhost:5000/api/createLcStatus
Content-Type: application/json

{
    "status" : "Not Found", 
    "description" : "Consignment yet not shipped"
}
###


post http://localhost:5000/api/createLC
Content-Type: application/json

{
    "fileNumber" : "abcd",
    "lcNumber" : "dgsdfgdg",
    "lcDate" : "2022-08-22T00:00:00.000Z",
    "piNumber" : "sdgsgs",
    "primarySupplierName" : "sgsfg",
    "secondarySupplierName" : "sdfsdffsd",
    "rm_id" : "6394953f5637a056d9c17d85",
    "shipmentDate" : [{"shipment" : "2022-12-11T10:16:16.232Z", "text" :"fwef"}],
    "origin" : "China"
}

### 
post http://localhost:5000/api/createSkuCategory
Content-Type: application/json

{
    "skuCategory" : "WanBao"
}





###
post http://localhost:5000/api/createPO
Content-Type: application/json

{
    "poNumber" : "sfssdsgg232424d",
    "poDate" : "2022-10-12",
    "partsOfPO" : [{
        "object_id" : "6398657223328b7eeff92374",
        "model_type" : "SFGBOM",
        "quantity" : 20,
        "supplierId" : "63a4597c63b510ab3cb62e8b",
        "unitPrice" : 10
    }]
}